### ISSUE TITLE
Make snapshot optional

### ISSUE THREAD

**Issue by vkruoso** [fleg/mongo-each#3]
Really great library! Thanks!

I need to iterate over a cursor with a sort applied, but the snapshot call on the cursor is not allowed when the sort is being used. It would be great to have an option to avoid using snapshot when not needed.

**Comment by fleg** [comment]
good point, I'll take a look at this

**Comment by fleg** [comment]
published as mongo-each@1.1.3

**Comment by vkruoso** [comment]
Awesome! Thanks @fleg.
